import "./globals.css";

import {  Inter, Montserrat } from "next/font/google";

const montserrat = Montserrat({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-montserrat",
});


export const metadata = {
  title: "Villanueva | Porfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={` ${montserrat.variable} font-montserrat`}>
 
      <body>{children}</body>
    </html>
  );
}
